ALTER TABLE challenges
    ADD COLUMN IF NOT EXISTS practice_mode VARCHAR(40) NOT NULL DEFAULT 'BUG_HUNT',
    ADD COLUMN IF NOT EXISTS mission_brief TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS success_criteria TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS reflection_prompt TEXT NOT NULL DEFAULT '';

ALTER TABLE progression_nodes
    ADD COLUMN IF NOT EXISTS practice_mode VARCHAR(40) NOT NULL DEFAULT 'BUG_HUNT',
    ADD COLUMN IF NOT EXISTS learning_objective TEXT NOT NULL DEFAULT '';

ALTER TABLE IF EXISTS learning_attempts
    ADD COLUMN IF NOT EXISTS practice_mode VARCHAR(40) NOT NULL DEFAULT 'BUG_HUNT';

ALTER TABLE IF EXISTS learning_category_stats
    ADD COLUMN IF NOT EXISTS recommended_mode VARCHAR(40) NOT NULL DEFAULT 'BUG_HUNT';
